### ISSUE TITLE
Is it possible to add a mode so that the expression does not add Spaces directly, like matlab comes with it

### ISSUE THREAD

**Issue by Giant-Turtle** [affenwiesel/matlab-formatter-vscode#100]
Is it possible to add a mode so that the expression does not add Spaces directly, like matlab comes with it

**Comment by affenwiesel** [comment]
Isn't adding/removing spaces the whole point of formatting?

**Comment by Giant-Turtle** [comment]
For a physical formula, we often write a very long expression in matlab. If we add spaces at that, the expression will become more more more longer. In matlab editor, it only cares if you have the right indent.

Thank you for providing this plug-in. I like it very much!

**Comment by Giant-Turtle** [comment]
> For a physical formula, we often write a very long expression in matlab. If we add spaces at that, the expression will become more more more longer. In matlab editor, it only cares if you have the right indent.
> 
> Thank you for providing this plug-in. I like it very much!

**Comment by affenwiesel** [comment]
I see. 

The way the programm is written, such an option would lead to very ugly formatting, though. This is because I first remove all spaces and then add new ones as appropriate. Omitting the adding of new spaces would therefore lead to code with no spaces whatsoever. I doubt that this is what you want, just to spare a few spaces in one formula...

Maybe a better solution would be an option to disable the formatter for the next line(s) of code?
There is actually an old issue requesting this... #58

**Comment by affenwiesel** [comment]
An option to ommit wrapping operators with spaces has been added.
Also, the probably better solution, as suggested above, has been included in the latest update.
