### ISSUE TITLE
code breaking formatting

### ISSUE THREAD

**Issue by rick3rt** [affenwiesel/matlab-formatter-vscode#32]
Hi, awesome extension! Just started using it, and came across some cases in which the formatter either breaks the code or just wrongly formats.

The statement 
```
addpath ../../functions
```
is getting formatted to:
```
addpath . ./ . ./ functions
```
which breaks the code. I can avoid this from happening by using `addpath(fullfile('..', '..','functions'));`, but that's a rather long expression... 

Another case, when trying to save the entire workspace except for some variables(s):
```
save matFileName -regexp ^(?!(var1ToExclude|var2ToExclude)$).
```
this will be formatted to:
```
save matFileName - regexp^(?!(var1ToExclude|var2ToExclude)$).
```
which does not work anymore. 

And then a last (minor) bug: 
```
% this is a test, to be continued...
a = 10;
```
will be reformatted to: 
```
% this is a test, to be continued...
    a = 10;
```
So it looks like it is interpreting the `...` at the end of the comment as a multi-line statement (as fixed in [issue 19](https://github.com/affenwiesel/matlab-formatter-vscode/issues/19)).

**Comment by affenwiesel** [comment]
Hi.
Theoretically I could 'fix' the first two issues. But this would require to handle `addpath `and `save ` as specific symbols like `%`, such that everything following the expression will not be formatted at all. However I don't like that approach because there might be various other matlab functions that can be called in this specific way.
Therefore I suggest to use the regular syntax for matlab functions which requires the arguments to be quoted e.g.
`addpath('../../functions')`
`save(matFileName, '-regexp', '^(?!(var1ToExclude|var2ToExclude)$)')`
This way everything is formatted correctly and in my optinion it also is easier to read.
Regarding the last issue, though I will upload a fix.

**Comment by rick3rt** [comment]
Hi, thx for your reply, and fix of the last issue! I get why you prefer not to change the behavior in the other cases. 

I came across another issue, that may be related: 
```
A = magic(3);
a = A./A
b = A./-A
c = A/-A
```
Will be formatted to: 
```
A = magic(3);
a = A ./ A
b = A. /- A
c = A /- A
```
Statement `a` and `c` are still fine, however `c` is wrongly formatted. Placing the brackets solves the issue, i.e. `A./(-A)`, and of course placing the minus at the beginning. I understand if you don't want to fix this, but let me know what you think.

Perhaps I have some weird/lazy coding practices

**Comment by affenwiesel** [comment]
Personally I would probably use brackets in such a case ;)
However I still think the formatter should not break the code if there aren't any. Therefore I fixed the behaviour for unitary minus in the last update.
Thanks for all the feedback.
