### ISSUE TITLE
Add double spaces in certain situations

### ISSUE THREAD

**Issue by marcelfarres** [affenwiesel/matlab-formatter-vscode#53]
This bug appeared on the last version. 

Here are some of the examples:
`hs = DataHash({fileInfo, preStimTime},  'array',  'SHA-1',  'HEX');`
`err =  'Time index is bigger ...`

**Comment by affenwiesel** [comment]
Hi, as with the previous update - whenever I fix an error concerning the whitespaces, the fix introduces a new error of that sort. It's like a bug-hydra (or maybe hydra-bug...).
Anyhow, while I could reproduce, and also fix the error in your first example, I'm not sure what to do about the second one. Is your issue, that in the line following the ellipsis ('...') the code is being indented? If so, this is intentional. Strings that are broken over several lines this way are not expected, though. Personally I'm not using Matlab but Octave where this is not even supported.  
The way my formatter is implemented at the moment, it will also be very tricky to find out that something is indeed a string if it doesn't end in the same line where it starts. 
Finally, I believe that this is also a corner case not too many people will ever run into.
For those reasons this issue will not be a top priority for now.

**Comment by marcelfarres** [comment]
Hello;

Update to last version 2.6.0 and both errors where solve. 

The second one was not on the multiline, there was a double space between = and ', I don't know why when I try to update the comment to reflect it deletes the double space automatically ... 

Anyway, this second problem is also solved by the last update. 

Thank you very much!
