### ISSUE TITLE
Line continuation is not working inside arrays

### ISSUE THREAD

**Issue by FFV47** [affenwiesel/matlab-formatter-vscode#62]
Line continuation is not working inside arrays, for example:
```matlab
[a, b, ...
c, d]
```
returns a error. It's working inside cell arrays though.

**Comment by affenwiesel** [comment]
It does work if you say:
```
A=[a, b, ...
c, d]
```
For cell-arrays the problem is actually the same for me...
I want to point out, that it is not necessary to put an ellipsis ('...') when breaking lines inside an array. (at least thats the case in octave)
However, the problem occurs regardless of the ellipsis , when you begin a line directly with the multiline (cell-)array.
I'll look into it!
